export type MediaKind = 'anime' | 'manga';
export type Title = { id: number; kind: MediaKind; name: string; score?: number | null; status: string };
export type Character = { id: number; name: string; image: string | null; favorites?: number | null; url: string };
export type PoolCharacter = Character & { titles: Title[]; power?: import('./power').Power };
export type JourneyCharacter = PoolCharacter & { instanceId: string; baseStats: import('./stats').BaseStats; statRarity: import('./stats').Rarity };
export type ImportState = 'queued' | 'listing' | 'fetching' | 'complete' | 'partial' | 'error' | 'cancelled';
export type Job = {
  id: string;
  username: string;
  scope?: string;
  starterTeam?: (PoolCharacter | JourneyCharacter)[];
  encounter?: { teams: JourneyCharacter[][]; result?: { left: number; right: number; mode?: 'idle' | 'clout'; winner?: 'left' | 'right' | 'draw' }; replay?: import('./autobattle').BattleReplay; rewardUsed?: boolean };
  demo: boolean;
  includePlanned: boolean;
  state: ImportState;
  createdAt: string;
  updatedAt: string;
  titles: Title[];
  listed: boolean;
  done: string[];
  failures: Record<string, string>;
  pool: Record<string, PoolCharacter>;
  message: string;
};
export type JobView = Omit<Job, 'titles' | 'done' | 'pool' | 'failures' | 'listed'> & {
  total: number;
  processed: number;
  failed: number;
  uniqueCharacters: number;
  favoriteCounts: number[];
  ratedFavoriteCounts: (number | null)[];
  unknownFavorites: number;
  failures: { title: string; message: string }[];
};
export const titleKey = (title: Pick<Title, 'id' | 'kind'>) => `${title.kind}:${title.id}`;
